"""Large-scale accuracy comparison: the real production KeywordClassifier
(ground truth, captured by control-plane/software_baseline_bench/matchrate/
against real Chatbot Arena traffic) vs. the DPA-realistic algorithm
(DpaMatcher, "folded" mode — the same case-folding simplification the real
C kernel in data-plane/dpa_decision_fastpath/ implements) on the exact same
23,448 real queries.

This extends the original accuracy_study (34 hand-curated queries) to a
real, large, well-known corpus — the number that actually matters for a
"does this generalize" argument, per the same reasoning that motivated
switching the benchmark corpus.

Run: python3 large_corpus_accuracy.py
Requires: control-plane/software_baseline_bench/data/software_ground_truth.json
(generated by `go run matchrate/main.go` in that directory — not committed,
regenerate locally, same as the query corpus itself).
"""

from __future__ import annotations

import json
from pathlib import Path

from decision_model import KeywordRule
from dpa_adapted import DpaMatcher

GROUND_TRUTH_PATH = Path(__file__).parent.parent / "software_baseline_bench" / "data" / "software_ground_truth.json"

# Identical to realKeywordRules() in keyword_bench_test.go and
# build_real_rule_table() in fastpath_bench_main.c — same 4 rules, same
# order (first-match-wins, matching ClassifyWithKeywordsAndCount's real
# semantics).
RULES: list[KeywordRule] = [
    KeywordRule(name="code_keywords", operator="OR", keywords=["code", "function", "debug", "algorithm", "refactor"]),
    KeywordRule(
        name="machine_learning",
        operator="OR",
        keywords=["machine learning", "model training", "gradient", "neural network", "classifier"],
    ),
    KeywordRule(name="urgent_keywords", operator="OR", keywords=["urgent", "immediate", "asap", "emergency"]),
    KeywordRule(
        name="fuzzy_sensitive_keywords",
        operator="OR",
        keywords=["social security", "credit card", "password", "api key"],
    ),
]


def dpa_classify(matcher: DpaMatcher, text: str) -> str:
    """Mirrors ClassifyWithKeywordsAndCount's first-match-wins semantics."""
    for rule in RULES:
        if matcher.evaluate_rule(rule, text).matched:
            return rule.name
    return ""


def main() -> None:
    if not GROUND_TRUTH_PATH.exists():
        raise SystemExit(
            f"{GROUND_TRUTH_PATH} not found — run `go run matchrate/main.go` in "
            "control-plane/software_baseline_bench first (needs the real corpus "
            "from data/download_chatbot_arena.py too)."
        )

    with open(GROUND_TRUTH_PATH) as f:
        ground_truth = json.load(f)

    matcher = DpaMatcher(case_mode="folded", rules=RULES)

    agree = 0
    both_no_match = 0
    both_match_same = 0
    software_match_dpa_miss = 0
    software_no_match_dpa_hit = 0
    both_match_different = 0

    mismatches: list[tuple[str, str, str]] = []

    for row in ground_truth:
        text = row["query"]
        sw_category = row["category"]
        dpa_category = dpa_classify(matcher, text)

        if sw_category == dpa_category:
            agree += 1
            if sw_category == "":
                both_no_match += 1
            else:
                both_match_same += 1
        else:
            if len(mismatches) < 20:
                mismatches.append((text, sw_category, dpa_category))
            if sw_category != "" and dpa_category == "":
                software_match_dpa_miss += 1
            elif sw_category == "" and dpa_category != "":
                software_no_match_dpa_hit += 1
            else:
                both_match_different += 1

    total = len(ground_truth)
    print(f"Large-corpus accuracy: DPA-realistic (folded) vs. real software KeywordClassifier")
    print(f"  corpus: {total} real Chatbot Arena queries")
    print(f"  agreement: {agree}/{total} = {100 * agree / total:.2f}%")
    print(f"    both no-match:        {both_no_match} ({100 * both_no_match / total:.2f}%)")
    print(f"    both matched, same rule: {both_match_same} ({100 * both_match_same / total:.2f}%)")
    print(f"  disagreement: {total - agree}/{total} = {100 * (total - agree) / total:.2f}%")
    print(f"    software matched, DPA missed (false negative for DPA): {software_match_dpa_miss}")
    print(f"    software no-match, DPA matched (false positive for DPA): {software_no_match_dpa_hit}")
    print(f"    both matched, but different rule: {both_match_different}")

    # Precision/recall on "did ANY rule match" as the positive class —
    # matches the framing already used in README.md's strict/folded results.
    sw_positive = sum(1 for r in ground_truth if r["category"] != "")
    tp = both_match_same + both_match_different  # DPA also matched something
    fn = software_match_dpa_miss
    fp = software_no_match_dpa_hit
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    print(f"\n  binary (any-match) precision={precision:.3f} recall={recall:.3f} f1={f1:.3f}")
    print(f"  software's real positive rate on this corpus: {sw_positive}/{total} = {100 * sw_positive / total:.2f}%")

    print("\n  sample disagreements:")
    for text, sw, dpa in mismatches:
        print(f"    sw={sw or '(none)':<26} dpa={dpa or '(none)':<26} {text[:80]!r}")


if __name__ == "__main__":
    main()
